export const READ_STATUS_REQUEST = 'READ_STATUS_REQUEST';
export const READ_STATUS_SUCCESS = 'READ_STATUS_SUCCESS';
export const READ_STATUS_FAILURE = 'READ_STATUS_FAILURE';
export const DISABLE_BUTTON = 'DISABLE_BUTTON';
